### ISSUE TITLE
Stellar Core prebuilt binaries for both amd and arm architectures

### ISSUE THREAD

**Issue by urvisavla** [stellar/go#4920] opened 2023-06-16 21:47 UTC
### What problem does your feature solve? ###

Lack of access to multi-platform prebuilt Stellar Core binaries for both linux/amd64 and linux/arm64 architectures of which the binary is required for horizon runtime with captive core ingestion.

### What would you like to see?

Prebuilt multi-arch Stellar Core binaries for both linux/arm64 and linux/amd64 are available as additional artifact links in the [Horizon GitHub releases](https://github.com/stellar/stellar-core/releases). 

Currently, multi-arch pre-built Horizon binaries are provided for amd and arm in [Horizon GitHub releases](https://github.com/stellar/go/releases). 

Since Horizon captive core ingestion depends on Stellar Core binary, this simplifies the process for Horizon users by allowing them to download both Horizon and Stellar Core binaries for the same architecture at the same time from one place. Otherwise the process to obtain stellar core binary for non-amd architectures requires additional steps such as compiling core from correct version of source and compile flags on a host that is on target architecture or cross compiling, which is non-trivial.

### What alternatives are there?
* people on amd architectures manually compile core from source or get core bin from debian package for the release they want to use as captive core bin for horizon.
* people on arm architectures manually compile core from source for the release they want to use as captive core bin for horizon.

**Comment by leighmcculloch** [comment] 2023-06-16 21:51
I think this is a duplicate of https://github.com/stellar/packages/issues/154. @urvisavla can you engage on that issue? Thanks!

**Comment by mollykarcher** [comment] 2023-09-11 18:45
Closing not because work is completed, but because it's being tracked by https://github.com/stellar/packages/issues/154

Once complete, we should update our docs to reflect that change, wherever its referenced

**Closed** 2023-09-11 18:44 UTC
Labels: feature request, partner-experience
