### ISSUE TITLE
Horizon throwing SQL error on GET /accounts/:id

### ISSUE THREAD

**Issue by jmbrito01** [stellar/go#986] opened 2019-03-07 17:09 UTC
I'm getting this error whenever i try to retrieve informations about a single account (the root wallet)

Error received in HTTP:
```
{
  "type": "https://stellar.org/horizon-errors/server_error",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/services/horizon/internal/issues. Please include this response in your issue."
}
```

Error in Horizon logs:
`horizon_1                  | time="2019-03-07T17:00:24.019Z" level=error msg="get failed: sql: Scan error on column index 0, name \"signers\": unsupported Scan, storing driver.Value type <nil> into type *string" pid=1 req=10f3a19d52a6/0m9zFsNOGp-000022 stack="[main.go:43 session.go:106 session.go:83 signer.go:23 actions_account.go:64 actions_account.go:37 base.go:186 actions_account.go:35 base.go:57 main_generated.go:10 init_web.go:100 server.go:1964 mux.go:418 mux.go:354 server.go:1964 mux.go:69 mux.go:295 server.go:1964 mux.go:418 mux.go:354 server.go:1964 mux.go:69 mux.go:295 server.go:1964 mux.go:418 mux.go:354 server.go:1964 http.go:73 server.go:1964 cors.go:190 server.go:1964 compress.go:66]"`

Horizon info:
```
{
  "_links": {
    "account": {
      "href": "http://localhost:8000/accounts/{account_id}",
      "templated": true
    },
    "account_transactions": {
      "href": "http://localhost:8000/accounts/{account_id}/transactions{?cursor,limit,order}",
      "templated": true
    },
    "assets": {
      "href": "http://localhost:8000/assets{?asset_code,asset_issuer,cursor,limit,order}",
      "templated": true
    },
    "metrics": {
      "href": "http://localhost:8000/metrics"
    },
    "order_book": {
      "href": "http://localhost:8000/order_book{?selling_asset_type,selling_asset_code,selling_asset_issuer,buying_asset_type,buying_asset_code,buying_asset_issuer,limit}",
      "templated": true
    },
    "self": {
      "href": "http://localhost:8000/"
    },
    "transaction": {
      "href": "http://localhost:8000/transactions/{hash}",
      "templated": true
    },
    "transactions": {
      "href": "http://localhost:8000/transactions{?cursor,limit,order}",
      "templated": true
    }
  },
  "horizon_version": "v0.17.3",
  "core_version": "v10.2.0-86-g8d180be",
  "history_latest_ledger": 278,
  "history_elder_ledger": 124,
  "core_latest_ledger": 278,
  "network_passphrase": "Internal Network ; March 2019",
  "current_protocol_version": 0,
  "core_supported_protocol_version": 10
}
```

Core info:
```
"info" : {
      "build" : "v10.2.0-86-g8d180be",
      "history_failure_rate" : "0",
      "ledger" : {
         "age" : 2,
         "baseFee" : 100,
         "baseReserve" : 100000000,
         "closeTime" : 1551978088,
         "hash" : "526a8a55731496134758b363f0b080d1f75d940e7748ac871dd90af8589a107b",
         "maxTxSetSize" : 100,
         "num" : 286,
         "version" : 0
      },
      "network" : "Internal Network ; March 2019",
      "peers" : {
         "authenticated_count" : 0,
         "pending_count" : 0
      },
      "protocol_version" : 10,
      "quorum" : {
         "286" : {
            "agree" : 1,
            "delayed" : 0,
            "disagree" : 0,
            "fail_at" : 0,
            "hash" : "6f408f",
            "missing" : 0,
            "phase" : "EXTERNALIZE",
            "validated" : true
         }
      },
      "startedOn" : "2019-03-07T16:37:47Z",
      "state" : "Synced!"
   }
}
```

Stellar core config
```
HTTP_PORT=11626
PEER_PORT=11625
PUBLIC_HTTP_PORT=true
RUN_STANDALONE=false

NETWORK_PASSPHRASE="Internal Network ; March 2019"
NODE_SEED="*** self"
NODE_IS_VALIDATOR=true

NODE_NAMES=[
  
]
KNOWN_PEERS=[
  
]

PREFERRED_PEERS=[
  
]

PREFERRED_PEER_KEYS=[
  
]

DATABASE="postgresql://dbname=core user=stellar password=*** host=postgres-node-1"

FAILURE_SAFETY=0
CATCHUP_RECENT=60480
UNSAFE_QUORUM=true
KNOWN_CURSORS=["HORIZON"]

[QUORUM_SET]
THRESHOLD_PERCENT=67
VALIDATORS=[
  "$self"
  
]

[HISTORY.local]
get="cp /opt/stellar/historyarchive/{0} {1}"
put="cp {0} /opt/stellar/historyarchive/{1}"
mkdir="mkdir -p /opt/stellar/historyarchive/{0}"
```

Horizon env configurations:
```
DATABASE_URL=postgres://stellar:***@postgres-node-horizon-1/horizon?sslmode=disable
STELLAR_CORE_DATABASE_URL=postgres://stellar:***@postgres-node-1/core?sslmode=disable
STELLAR_CORE_URL=http://stellar-node-1:11626
NETWORK_PASSPHRASE=Internal Network ; March 2019
INGEST=true
```

I'm also using [satoshipay/stellar-horizon](https://github.com/satoshipay/docker-stellar-horizon) as the main horizon docker image and stellar/stellar-core as the core image.

Do any of you know what is causing this error?

**Comment by bartekn** [comment] 2019-03-07 19:02
Duplicate of https://github.com/stellar/go/issues/967. TL;DR switch to stable version of stellar-core.

**Closed by bartekn** 2019-03-07 19:02 UTC
