### ISSUE TITLE
ticker service is unable to upgrade the database

### ISSUE THREAD

**Issue by overcat** [stellar/go#1334] opened 2019-05-25 00:51 UTC
When I run ticker with Docker, the program prompts that the database cannot be upgraded.

My steps:
```bash
git clone https://github.com/stellar/go.git
cd go/services/ticker/
docker build -t ticker .
docker run --rm -it -p "8000:8000" ticker
# Enter password
```

Logs
```
Initializing Ticker

postgres user: stellar
Enter New Postgresql Password:
Confirm:
finalize-pgpass: ok
init-postgres: ok
postgres: up
create-ticker-db: ok
stellar-postgres-user: ok

Upgrading database to latest version

INFO[2019-05-25T00:36:20.344Z] Refreshing the asset database                 pid=87
INFO[2019-05-25T00:36:20.364Z] Upgrading the database                        pid=87
FATA[2019-05-25T00:36:20.385Z] could not upgrade the database:pq: syntax error at or near "AS"  pid=87
```

Some information that might be useful.
System Info
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch

Linux version 4.9.0-9-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13)
```

Docker Info
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-9-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.617GiB
Name: stellar-ticker
ID: 3ZZO:XXEO:UF3U:QQSP:KVUD:UK26:LBNS:BS62:3TWE:AQB3:NBRU:BWBV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

Hi, @accordeiro, can you confirm the issue.

**Comment by accordeiro** [comment] 2019-05-25 13:52
Hi @overcat 👋 Thanks for the report, I was able to reproduce the issue.

This happened because the current Docker config pulls the Ticker binary from the releases on a separate repo, and the binary wasn't up to date (it had the migrations set up for a different Postgres version, hence the `pq syntax error` – see #1204 if you'd like to see what changed).

This week, I'm planning to create a release on the monorepo and change the Docker setup to pull binaries directly from here. In the meantime, I've already updated the ticker binary, so this issue should be fixed.

Could you please run:

```sh
cd go/services/ticker/
docker build --no-cache -t ticker .
docker run --rm -it -p "8000:8000" ticker
```

And let me know if it works now? Thanks!

**Comment by overcat** [comment] 2019-05-25 14:15
Hi @accordeiro 👍 It works for me.

It's also worth pointing out that the third step of `Quick Start` in [README](https://github.com/stellar/go/blob/master/services/ticker/README.md) should be `docker build -t ticker .` This small mistake can confuse people who are unfamiliar with Docker.

In addition, why should we package PostgreSQL in this image? Is it a better choice to split it separately?

**Comment by accordeiro** [comment] 2019-05-28 13:21
You're right – it should be `docker build -t ticker .`

Would you like to send a PR to fix this? :)

**Comment by accordeiro** [comment] 2019-05-28 15:33
Thanks @overcat! I'll close this issue now.

**Closed by accordeiro** 2019-05-28 15:33 UTC
Labels: ticker
