### ISSUE TITLE
I encountered some errors，It will appear when you catch up to 35703671

### ISSUE THREAD

**Issue by shenhao217** [stellar/go#3656] opened 2021-06-02 18:58 UTC
Hello, I encountered some errors，It will appear when you catch up to 35703671
log:
time="2021-06-03T02:52:08.202+08:00" level=info msg="Tx: applying ledger 35703671 (txs:197, ops:460)" pid=22966 subservice=stellar-core
time="2021-06-03T02:52:08.562+08:00" level=warning msg="Could not prepare range" error="opening subprocess: Error fast-forwarding to 35703671: unmarshalling framed LedgerCloseMeta: xdr:decode: switch '19' is not valid enum value for union" pid=22966 preparedRange="[35703671,latest)" subservice=api
r

**Comment by bartekn** [comment] 2021-06-02 18:59
Duplicate of https://github.com/stellar/go/issues/3655. Please upgrade to the latest Horizon.

**Comment by shenhao217** [comment] 2021-06-02 18:59
horizon_version": "2.3.0-5029e28d1ec6272a44f5c03ad732059b2fead31d",
  "core_version": "stellar-core 17.1.0 (6c86d890d2e8d91324324701f5357c8cac5e3098)",

**Closed by bartekn** 2021-06-02 18:59 UTC
Labels: bug

**Comment by bartekn** [comment] 2021-06-02 19:04
Version 2.3.0 has support for Protocol 17. Are you running more than one Horizon instance? Can you verify the version by running `horizon version` command?

**Comment by shenhao217** [comment] 2021-06-02 19:18
[image: 51741622661471_.pic.jpg]
Hello, I am running a single instance

Bartek Nowotarski ***@***.***> 于2021年6月3日周四 上午3:04写道：

**Comment by shenhao217** [comment] 2021-11-02 16:24
Hello,I am executing horizon db migrate up and a log prompt appears
pq: relation "history_trades_60000" already exists handling
47_precompute_trade_aggregations.sql
