### ISSUE TITLE
Captive Core leaks zombie gzip and curl processes

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3217] opened 2020-11-11 14:49 UTC
After running `stellar/horizon:2cfb2670c` with captive core for about a day in a local kubernetes cluster, I noticed that a bunch of processes were unreaped:

```
$ kubectl exec -ti deployment/horizon  -- ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  7.6 10.5 1829000 214076 ?      Ssl  Nov10 111:30 ./horizon
root       937  0.0  0.0      0     0 ?        Z    Nov10   0:00 [curl] <defunct
root       942  0.0  0.0      0     0 ?        Z    Nov10   0:00 [curl] <defunct
root       944  0.0  0.0      0     0 ?        Z    Nov10   0:00 [gzip] <defunct
root       945  0.0  0.0      0     0 ?        Z    Nov10   0:00 [gzip] <defunct
root       946  0.0  0.0      0     0 ?        Z    Nov10   0:00 [gzip] <defunct
root       947  0.0  0.0      0     0 ?        Z    Nov10   0:00 [gzip] <defunct
root       948  0.0  0.0      0     0 ?        Z    Nov10   0:00 [gzip] <defunct
root       949  0.0  0.0      0     0 ?        Z    Nov10   0:00 [gzip] <defunct
root       950  0.0  0.0      0     0 ?        Z    Nov10   0:00 [gzip] <defunct
root       951  0.0  0.0      0     0 ?        Z    Nov10   0:00 [gzip] <defunct
root       952  1.2  6.2 1047204 126896 ?      Sl   Nov10  17:43 /usr/bin/stella
root      3027  0.0  0.1  34400  2792 pts/0    Rs+  14:36   0:00 ps aux
```

```
$ kubectl exec -ti deployment/horizon  -- bash -c 'apt-get install psmisc && pstree -a'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
[...]
horizon
  |-(curl)
  |-(curl)
  |-(gzip)
  |-(gzip)
  |-(gzip)
  |-(gzip)
  |-(gzip)
  |-(gzip)
  |-(gzip)
  |-(gzip)
  |-stellar-core --conf /etc/stellar/stellar-core.cfg run --in-memory --start-at-ledger 199934 --start-at-hash2ed85d1d43457
  |   `-11*[{stellar-core}]
  `-12*[{horizon}]
```

This is what I think happened:

1. Core (for whatever reason, maybe a crash) failed to wait for the `curl`/`gzip` processes before exiting, orphaning them
2. Since `horizon` is the init process, it inherits the orphaned processes. But, since `horizon` doesn't wait for orphaned processes (unlike it's expected from a normal init process), the processes become zombies.

This shouldn't be a problem in a non-containerized workload, and this is one of the reasons why [it's a bad idea to run multiple processes in the same container](https://devops.stackexchange.com/a/448).

Here are the full logs:  [logs.txt.gz](https://github.com/stellar/go/files/5524678/logs.txt.gz) (which I haven't investigated yet)

We should make sure that `Core` doesn't leave orphans behind but, if we want to continue with the multi-process antipattern, the containerized Horizon workloads should probably run an init process like https://github.com/krallin/tini

**Comment by 2opremio** [comment] 2020-11-11 15:29
CC @graydon

**Comment by graydon** [comment] 2020-11-12 23:35
Huh. I thought I commented on this the other day but it seems like not.

I'm happy to modify core to be more robust about reaping subprocesses when it's forcefully shut down: have added code to do so over here in https://github.com/stellar/stellar-core/pull/2801.

But I think you might also want to run with an init anyways, in case horizon crashes and fails to reap core.

(I also feel a _little_ weird about the notion that "one should not run multiple processes in a container"; taken literally this would exclude running either daemons that typically run multiprocess clusters themselves -- postgresql, apache, sshd -- or build-process containers that run `make` or whatever, or even the very common thing where container entrypoints are `/bin/sh` with a little bit of filesystem or environment fiddling before running the "real" final process.

Personally I'm a bit more inclined call this a design mistake in containers as a technology -- I suspect they _should_ just provide a mechanism for auto-reaping orphan zombies. Docker has already added built-in support for `tini` inside its containers, using an `--init` flag, and there's [a bug open for k8s to add the same](https://github.com/kubernetes/kubernetes/issues/84210). Arguably unix itself should, relying on init to do this seems like a bit of cutesy "unix minimalism" that could just as easily happen in the kernel, but I doubt anyone cares enough to change it outside the world of containers..)

**Comment by bartekn** [comment] 2020-12-07 10:40
I'm not 100% sure if the problem you (@2opremio) are describing here is zombie processes when Horizon exits or when Stellar-Core subprocess exit (and then Horizon potentially starting another subprocess). In the former case, I believe this should be fixed by #3258 + #3266. The problem is that we did not have a proper code for user-initiated shutdown and we did not call `LedgerBackend.Close()` on Horizon shutdown so it's possible that if you exit Horizon it will leave zombie Stellar-Core's.

**Comment by 2opremio** [comment] 2020-12-07 14:28
> I'm not 100% sure if the problem you (@2opremio) are describing here is zombie processes when Horizon exits or when Stellar-Core subprocess exit (and then Horizon potentially starting another subprocess).

It's the latter, those are processes left by Core. AFAIU if/when Horizon exits the container stops since the the command specified in the container's spec ended.

**Comment by bartekn** [comment] 2020-12-08 14:35
If it's not a Horizon issue can we close it / move to Stellar-Core repo?

**Comment by 2opremio** [comment] 2020-12-08 15:34
It's an issue with respect to how we containerize Horizon. Orphan children are unavoidable (you can always cause them by `kill -9`'ing the parent of the process) but it's up to us to containerize Horizon in a way in which init reaps them instead of causing zombie processes.

**Comment by 2opremio** [comment] 2020-12-08 15:35
(To be clear, It may be that Core can do better to reduce the number of orphans caused but it's always possible to cause them regardless of what Core does)

**Comment by bartekn** [comment] 2021-06-24 19:09
Can you still reproduce it using the latest version (2.5.0/2.5.1)? I wonder if the changes there fixed it.

**Comment by bartekn** [comment] 2021-12-20 14:44
Closing because the problem is either fixed or does not cause any issues.

**Closed by bartekn** 2021-12-20 14:44 UTC
Labels: horizon, fast-txmeta, bug
