### ISSUE TITLE
Horizon effects are broken on (at least some) path payments

### ISSUE THREAD

**Issue by istrau2** [stellar/go#788] opened 2018-12-14 01:51 UTC
See these two links:

1. https://horizon.stellar.org/operations/91610844969832449
2. https://horizon.stellar.org/operations/91610844969832449/effects

Note that the account debited effect does not match the op.sourceAmount.

**Comment by bartekn** [comment] 2019-01-14 16:54
Duplicate of https://github.com/stellar/go/issues/744.

**Closed by bartekn** 2019-01-14 16:54 UTC
Labels: horizon
