### ISSUE TITLE
horizon: `db reingest` starting from zero stops after first set

### ISSUE THREAD

**Issue by graydon** [stellar/go#3907] opened 2021-09-10 22:26 UTC
Reported from nyet @ blockdaemon in chat: `you set "start" to zero it will stop after the first set is done`

**Comment by nyetwurk** [comment] 2021-09-10 22:29
If `PARALLEL_JOB_SIZE` is less than the desired number of ledgers to ingest:

If you are using a single thread, ingest will exit as soon as that thread is done

If you have specified more than one thread via `--parallel-workers`, new threads will not be created, and as soon as the last one finishes, ingest will exit.

**Comment by 2opremio** [comment] 2021-09-14 12:55
@nyetwurk I have created a testcase with the conditions you mention at https://github.com/stellar/go/pull/3916 and I haven't been able to reproduce the problem.

@nyetwurk could you supply us with the exact commandline you used and the resulting logs? Thanks

**Comment by 2opremio** [comment] 2021-09-14 12:57
I suspect that ingestion may be exiting due to an error and not a problem in the parallelization login

**Comment by sreuland** [comment] 2021-11-30 20:35
Hello @nyetwurk , wanted to verify if this issue is still happening? If so, can you provide a copy of the command line your are running to invoke the horizon re-ingestion? Would like to see details on ledger range and whether it's test or pub net, etc., have been trying to replicate locally but not seeing the same observed behavior, thanks!

**Comment by sreuland** [comment] 2021-12-15 21:20
moving this to backlog for now until confirmation on how to replicate or confirm if obsoleted.

**Comment by bartekn** [comment] 2021-12-20 14:19
Closing because we couldn't reproduce. Please reopen with specific command to reproduce the issue.

**Closed by bartekn** 2021-12-20 14:19 UTC
Labels: bug
