### ISSUE TITLE
Issue: Streampayments contains empty memo fields

### ISSUE THREAD

**Issue by Pedity-Luffy** [stellar/go#1149] opened 2019-04-17 04:56 UTC
The Streampayments function in stellar go horizon, returns empty memo Type and memo Value. All other fields work fine. 
https://godoc.org/github.com/stellar/go/clients/horizon#Client.StreamPayments
https://godoc.org/github.com/stellar/go/clients/horizon#Payment
This issue is tested for memo type - ID, TEXT, HASH

An rough example is below -
```
	const address = "GBD3ECXAO4427NFYIZH6TYSZVX2I76KVUHYYKJIQZUYC3GHA73KHGNNV"

	ctx := context.Background()

	cursor := horizon.Cursor("98924319576453121")
horizon.DefaultPublicNetClient.StreamPayments(ctx, address, &cursor, func(payment horizon.Payment) {
		fmt.Println("Payment Memo Type", payment.Memo.Type)
		fmt.Println("Payment Memo Value", payment.Memo.Value)
}
```

To update the the payment structure, a user will have to run the mocking LoadMemo method and than Memo Data will be updated. For example
```
	const address = "GBD3ECXAO4427NFYIZH6TYSZVX2I76KVUHYYKJIQZUYC3GHA73KHGNNV"

	ctx := context.Background()

	cursor := horizon.Cursor("98924319576453121")
horizon.DefaultPublicNetClient.StreamPayments(ctx, address, &cursor, func(payment horizon.Payment) {
	        horizon.DefaultPublicNetClient.LoadMemo(&payment)
		fmt.Println("Payment Memo Type", payment.Memo.Type)
		fmt.Println("Payment Memo Value", payment.Memo.Value)
}
```
This should be default without using LoadMemo or should be updated in stellar godoc.

**Comment by ire-and-curses** [comment] 2019-04-22 20:05
Duplicate of #924.

**Closed by ire-and-curses** 2019-04-22 20:05 UTC

**Comment by Pedity-Luffy** [comment] 2019-04-23 04:10
@ire-and-curses : 
My suggestion related to the issue is that this information should be updated for Streampayments function in godocs or Streampayments should work without LoadMemo.

**Comment by ire-and-curses** [comment] 2019-04-23 04:24
@Pedity-Luffy I agree this should be clarified. @poliha lets confirm the behaviour in the new `horizonclient` and modify as needed.

**Comment by poliha** [comment] 2019-04-23 09:03
Memo is a field on transactions and not on operations; so it wont be populted when getting payments.  You will always need to get the memo with an extra API call. If we want memo on operations, there needs to be further discussions on that as it involves changes to horizon.

**Comment by Pedity-Luffy** [comment] 2019-04-23 11:24
@poliha As it will need discussion on this, I will suggest adding a note/comment on Streampayments function on godoc stating the use of LoadMemo for loading memo after streaming payments.

**Comment by poliha** [comment] 2019-05-14 13:47
See discussion for possible workaround in #1255. 
#1260 will be used to track implementation
