### ISSUE TITLE
Horizon timeout after transaction is added to ledger

### ISSUE THREAD

**Issue by oryband** [stellar/go#305] opened 2018-02-12 16:57 UTC
- See the following transaction: 
 https://horizon.stellar.org/transactions/335b869b7c9eb491291869b8b06b32582190395945cccb91457ba04774f3ace0
- This transaction was submitted to Horizon on `2018-02-12T15:12:19.31094599Z`. Looking at the transaction information, it was created on `2018-02-12T15:12:19Z`.
- Transaction added to ledger on: `2018-02-12T15:12:19Z` (~5 seconds after submission): https://horizon.stellar.org/ledgers/16230126
- Horizon replied with an HTTP 504 (Gateway Timeout) on `2018-02-12T15:13:19.434419221Z` (~1 minute after submission).
- I've used the golang SDK, and my `horizon.Client.HTTP.Timeout` is set to 2 minutes.

This is reproducible on 4 identical machines on DigitalOcean. The instances are on DO's zones FRA1, SFO1, SGP1, NYC1

Each node is running Horizon + Core (watcher, non-validating) using [stellar/quickstart docker image](https://hub.docker.com/r/stellar/quickstart/) with this commit: https://github.com/stellar/docker-stellar-core-horizon/commit/aad080792989a8082cbffc0f58bd8e481957af86

A local application submits transactions to the local Horizon on each node.

Here is the following Core and Horizon configuration in use:

```toml
# stellar/quickstart specific
HTTP_PORT=11626
PUBLIC_HTTP_PORT=true
LOG_FILE_PATH=""
DATABASE="postgresql://dbname=core host=localhost user=stellar password=1"
CATCHUP_RECENT=1024

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

NODE_NAMES=[
"GC5SXLNAM3C4NMGK2PXK4R34B5GNZ47FYQ24ZIBFDFOCU6D4KBN4POAE  satoshipay1",
"GBJQUIXUO4XSNPAUT6ODLZUJRV2NPXYASKUBY4G5MYP3M47PCVI55MNT  satoshipay2",
"GAK6Z5UVGUVSEK6PEOCAYJISTT5EJBB34PN3NOLEQG2SUKXRVV2F6HZY  satoshipay3",
"GCGWABAQ6OUOVUGWJVPRJ5LWBIWYN3CVOVOZYBNQQGIBRULQHYNGQ7GH  cryptomover1",
"GC7MH45NSXXPBLQJRSEVF2DFUVLGGYOJER5FRUNVCYVMXJYJT5LLQJW5  cryptomover2",
"GAENPO2XRTTMAJXDWM3E3GAALNLG4HVMKJ4QF525TR25RI42YPEDULOW  ibm_uk",
"GBJ7T3BTLX2BP3T5Q4256PUF7JMDAB35LLO32QRDYE67TDDMN7H33GGE  ibm_hong_kong",
"GCGB2S2KGYARPVIA37HYZXVRM2YZUEXA6S33ZU5BUDC6THSB62LZSTYH  sdf1",
"GCM6QMP3DLRPTAZW2UZPCPX2LF3SXWXKPMP3GKFZBDSF3QZGV2G5QSTK  sdf2",
"GABMKJM6I25XI4K7U6XWMULOUQIQ27BCTMLS6BYYSOWKTBUXVRJSXHYQ  sdf3",
]

KNOWN_PEERS=[
"core-live-a.stellar.org:11625",
"core-live-b.stellar.org:11625",
"core-live-c.stellar.org:11625",
"confucius.strllar.org",
#"stellar1.bitventure.co",
"stellar.256kw.com"
]

[QUORUM_SET]
#VALIDATORS=[
#"$eno", "$tempo.eu.com", "$satoshipay", "$cryptomover", "$umbrel", "$exodo", "$ibm", "$sdf_watcher1", "$sdf_watcher2", "$sdf_watcher3"
#]
VALIDATORS=[
"$sdf1", "$sdf2", "$sdf3", "$satoshipay1", "$satoshipay2", "$satoshipay3", "$cryptomover1", "$cryptomover2", "$ibm_uk", "$ibm_hong_kong"
]


[HISTORY.cache]
get="cp /opt/stellar/history-cache/{0} {1}"

[HISTORY.sdf1]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_001/{0} -o {1}"

[HISTORY.sdf2]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_002/{0} -o {1}"

[HISTORY.sdf3]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_003/{0} -o {1}"
```
```bash
#!/bin/bash

export DATABASE_URL="postgres://stellar:1@localhost/horizon"
export STELLAR_CORE_DATABASE_URL="postgres://stellar:1@localhost/core"
export STELLAR_CORE_URL="http://localhost:11626"
export LOG_LEVEL="info"
export INGEST="true"
export PER_HOUR_RATE_LIMIT="72000"
export NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
```
It looks like the configuration is OK, no idea why I'm getting the timeouts.

**Comment by oryband** [comment] 2018-02-12 17:22
A node that succeeds submitting transaction returns the following `/metrics` response:
```javacriptj
"txsub.buffered": {
    "value": 0
// ...
  "txsub.open": {
    "value": 11
```
Nodes that are timing out return the following:
```javascript
"txsub.buffered": {
    "value": 0
// ...
  "txsub.open": {
    "value": 58
```

**Comment by oryband** [comment] 2018-02-13 10:29
Possibly related issues:
- stellar/horizon#369
- stellar/horizon#354

**Comment by oryband** [comment] 2018-02-14 11:04
I've managed to bypass the issue by not using the quickstart docker image. I created an alternative setup similar to the above, but on AWS. At first I tried to used the quickstart docker image but got the same results - not a single successful transaction, all timed out.

Afterwards I decided to abandon the docker image and setup my ow PostgreSQL on RDS, and four EC2 instances in four different regions globally, and the problem has disappeared completely.

**Comment by bartekn** [comment] 2018-02-14 19:21
Moving to https://github.com/stellar/docker-stellar-core-horizon/issues/41.

**Comment by s-a-y** [comment] 2018-02-26 12:20
Have the same issue, but not using quickstart docker image

**Comment by andrenarchy** [comment] 2018-07-09 21:35
It doesn't look like this is related to the docker image (I can imagine it's not related to docker at all). We currently have one Horizon that is timing out with 504s for all transactions that are submitted to it. Anything I can do to help debugging this?

**Comment by andrenarchy** [comment] 2018-07-09 21:41
Hm, I just set `LOG_LEVEL=debug` and after restarting Horizon the 504s disappeared. We keep getting this issue frequently – any idea what we can do next time it happens?

**Comment by bartekn** [comment] 2018-07-12 14:41
@andrenarchy what's the average tx submission rate to all your Horizon instances?

**Comment by bartekn** [comment] 2018-07-12 16:05
I think I'm able to reproduce it, going to debug it now.

**Comment by andrenarchy** [comment] 2018-07-12 20:08
@bartekn cool, keep me posted! When Horizon was in this state it was enough to submit a single transaction to get the 504. The instance might have seen a large tx submission rate before though.

**Comment by bartekn** [comment] 2018-07-16 15:56
After checking the `txsub` package in Horizon and running several tests I think that the issue discussed here is not a bug in Horizon but a lack of proper documentation for `Timeout` errors.

First let me explain how `txsub` package work (simplified): when it sees a new transaction sent via `POST /transactions` endpoint it is forwarding it to the Core's `/tx` endpoint that is responsible for checking and then propagating a new transaction to the network. If Horizon sees `PENDING` response it starts monitoring `txhistory` table of the Core DB and if it can't see a newly submitted transaction for `SubmissionTimeout` (currently equal 1 minute) it sends `Timeout` error response.

Now, why Core doesn't add a new transaction to `txhistory`? This table contains only the transactions that were included in the ledger and if a new transaction is not included in 3 consecutive ledgers it's removed from the queue. This can happen when ledgers are full and network can't add extra transactions above `max_tx_set_size` (currently 50 in Stellar Public Network).

So what's the workaround in case of such situation? Developers have two options:
1. You can keep resubmitting the transaction (with the same sequence number) until it is included in the ledger.
2. You can increase the [fee](https://www.stellar.org/developers/guides/concepts/fees.html).

Core team is discussing a new fee model in https://github.com/stellar/stellar-protocol/issues/133 that's basically changing `fee` to `max_fee`. This will make submitting transactions cheaper in a future (higher fee only when needed).

This issue will be closed after merging https://github.com/stellar/go/pull/541 which updates the documentation.

**Comment by andrenarchy** [comment] 2018-07-17 07:53
Thanks for the explanation @bartekn!

However, this does not explain the issue for me. We observe that the transaction is actually included pretty much immediately after submitting it to Horizon (usually the next ledger). This is also what @oryband described above. Thus I don't see how the window of 3 consecutive ledgers in `txhistory` explains the behavior.

@bartekn can you please reopen the issue?

**Comment by bartekn** [comment] 2018-07-17 07:59
@andrenarchy can you confirm that response body you're getting is sent by Horizon, i.e. it looks like this: https://github.com/stellar/go/blob/master/services/horizon/internal/render/problem/main.go#L64 Are you using any reverse proxy or communicate with Horizon directly?

> Thus I don't see how the window of 3 consecutive ledgers in txhistory explains the behavior.

I will confirm with the Core team if this behaviour has been changed recently.

**Comment by s-a-y** [comment] 2018-08-28 03:34
Yes, issue I had is not caused by high load.
When it happens - all transaction are getting successfully included into ledger, but Horizon always returns 504. I mean I wasn't able to get 200 response at all for any posted tx.
I believe it has something to do with misconfigured communication between horizon and stellar-core. I was able to overcome it when switched to different docker setup, so never really needed to dig deeper.
I wasn't using quickstart image.

**Comment by ratikesh9** [comment] 2018-08-28 08:03
Yes @s-a-y  this is not caused on high load as the transaction which I am submitting to horizon server is much low than 50 TPS and moreover the transaction gets included to ledger but still the horizon gets timeout.

@bartekn  can you check this?

**Comment by bartekn** [comment] 2018-08-29 15:53
OK, it's possible that it's some obscure sync issue (like https://github.com/stellar/go/pull/603). Will try to debug it again.

**Comment by gituser** [comment] 2018-09-11 21:12
Hi.

So what's up with this issue? Has it been fixed? Or what is a proper workaround how to deal with horizon if it returns 504 error? How to make sure that the transaction has been submitted and get it's resulting hash?

We've just stumbled upon it and don't know how to resolve it and get proper response from horizon that transaction has been successfully submitted.

Thanks.

**Comment by i3bitcoin** [comment] 2018-09-14 18:02
@gituser 
Try to change in horizon.env this row
export LOG_LEVEL="info"
to
export LOG_LEVEL="debug"

It worked for me.

**Comment by gituser** [comment] 2018-09-14 18:56
> @gituser
> Try to change in horizon.env this row
> export LOG_LEVEL="info"
> to
> export LOG_LEVEL="debug"
> 
> It worked for me.

What LOG_LEVEL has to do with timeouts? I've just checked I had already `LOG_LEVEL="debug"` so the issue is something else.

**Comment by i3bitcoin** [comment] 2018-09-16 09:42
Don't know, may be a coincidence, I've followed the suggestion of this guy

> Hm, I just set `LOG_LEVEL=debug` and after restarting Horizon the 504s disappeared. We keep getting this issue frequently – any idea what we can do next time it happens?

**Comment by fairdrop** [comment] 2018-09-19 01:05
changing LOG_LEVEL didn't work for me - still 504, also using docker quickstart

**Comment by skyscraperV** [comment] 2018-10-14 21:51
we use docker image to build a private stellar network(about 10 nodes) , many  504 tiemeout .
but when only one node standalone mode ,there is not 504 timeout

**Comment by skyscraperV** [comment] 2018-10-15 01:49
we use lastest docker image 
horizon_version: "v0.14.2",
core_version: "v10.0.0",

**Comment by andrenarchy** [comment] 2018-10-17 07:57
Unfortunately we've seen more 504 errors from Horizon this morning too. The transactions seem to have been included in the ledger despite the errors.

**Comment by bartekn** [comment] 2018-10-17 09:11
@andrenarchy can you send the logs around the time you were experiencing this?

**Comment by andrenarchy** [comment] 2018-10-17 19:18
@bartekn ok, I found out why I didn't see anything in our logs... the reason is: the code we were running was using SDF's Horizon server :sweat_smile: – maybe you can see 504s between 2018-10-17T06:25:00Z and 2018-10-17T06:41:00Z in your logs?

**Comment by bartekn** [comment] 2018-10-17 19:19
I can try. What's the tx hash for the transaction that timed out but was included?

**Comment by bartekn** [comment] 2018-10-19 11:44
Related stellar-core issue: https://github.com/stellar/stellar-core/issues/1811

**Comment by gituser** [comment] 2018-12-02 12:58
I just had again this error on fresh `v0.15.2` stellar-horizon version (I'm running my own node):

```
transferMoney returned in exception Server error: `POST http://x.x.x.x:8000/transactions` resulted in a `504 Gateway Timeout` response: { "type": "https://stellar.org/horizon-errors/timeout", "title": "Timeout", "status": 504, "detail": "Your reque (truncated...)
```

**Comment by gituser** [comment] 2018-12-02 19:14
I had to rollback to `v0.14.2` because `v0.15.1` is giving me 504 error when I try to send a transaction.

**Comment by slavkomae** [comment] 2018-12-04 05:39
I'm consistently encountering this problem for each transaction I try posting on 0.14.2/10.0.0. Have to resort to using SDF servers.

**Comment by gituser** [comment] 2018-12-04 08:21
@slavkomae interestingly I have this issue only on newere `v0.15.1` horizon and on `v0.14.2` it works for me.

**Comment by slavkoKoneksa** [comment] 2018-12-04 15:44
@gituser I switched LOG_LEVEL to "debug" and restarted the server -- as suggested above -- and that resolved the issue, at least for now. It's been working for a few hours now without it re-occurring.  Of course, since nobody has any idea how or why that would resolve the issue, I have no confidence that it won't come back. I'll report back in a few days either way.

**Comment by slavkonoodle** [comment] 2018-12-05 20:06
@gituser For me, setting LOG_LEVEL to debug and restarting worked.

Now if I only knew why...

**Comment by bartekn** [comment] 2018-12-06 18:46
The `txsub` code [did not](https://github.com/stellar/go/compare/horizon-v0.14.2...horizon-v0.15.0) really change between 0.14.2 and 0.15.1. When you receive Timeout response you should continue as described in: https://www.stellar.org/developers/horizon/reference/errors/timeout.html.

If you are constantly having this issue it means that your stellar-core has problems with communicating with the network (ie. transaction submission will not work if your node is not synced correctly) or the network is congested at the moment and you just need to try again.

If you want to receive a final state of a transaction in a defined time please add a [`timebound.max_time`](https://www.stellar.org/developers/guides/concepts/transactions.html#time-bounds) on your transaction. We're in the process of updating SDKs to give you a better control of timeouts. [Java SDK 0.4.0](https://github.com/stellar/java-stellar-sdk/releases/tag/0.4.0) already has a support for this, other SDKs will follow.

I am going to close this as it's not Horizon issue - Horizon just forwards the transaction to stellar-core and waits for results. It has no control over how the transaction is broadcasted in the network.

**Comment by oryband** [comment] 2018-12-23 15:04
temporary solution that worked for me: https://github.com/stellar/docker-stellar-core-horizon/issues/41#issuecomment-449642075

**Comment by gituser** [comment] 2018-12-28 15:50
> The `txsub` code [did not](https://github.com/stellar/go/compare/horizon-v0.14.2...horizon-v0.15.0) really change between 0.14.2 and 0.15.1. When you receive Timeout response you should continue as described in: https://www.stellar.org/developers/horizon/reference/errors/timeout.html.
> 
> If you are constantly having this issue it means that your stellar-core has problems with communicating with the network (ie. transaction submission will not work if your node is not synced correctly) or the network is congested at the moment and you just need to try again.
> 
> If you want to receive a final state of a transaction in a defined time please add a [`timebound.max_time`](https://www.stellar.org/developers/guides/concepts/transactions.html#time-bounds) on your transaction. We're in the process of updating SDKs to give you a better control of timeouts. [Java SDK 0.4.0](https://github.com/stellar/java-stellar-sdk/releases/tag/0.4.0) already has a support for this, other SDKs will follow.

The issue has nothing to do with timeout. The transaction gets included in 1 second in the ledger and transaction time indicates that, so the question is why horizon responds with 504 whilst in fact the transaction has been included in 1 second right after posting?

> 
> I am going to close this as it's not Horizon issue - Horizon just forwards the transaction to stellar-core and waits for results. It has no control over how the transaction is broadcasted in the network.

Of course, but horizon is used to send this transaction to the stellar network so for many applications this is an issue right there. Something timeouts means transaction wasn't successful but in fact it was.

**Comment by oryband** [comment] 2019-01-17 10:04
Please note this comment https://github.com/stellar/docker-stellar-core-horizon/issues/41#issuecomment-454355150

**Comment by bartekn** [comment] 2019-01-17 12:35
@oryband I've received a bunch of logs from Lumenauts and after analyzing them I think I found the issue (#815). It's now in review and will be released later today.

**Comment by oryband** [comment] 2019-01-17 13:33
@bartekn looks like the PR solves the issue, I have an environment where I can reproduce this and it doesn't appear anymore when testing with the above branch. See my comment on the PR.

**Closed** 2019-01-17 18:22 UTC
Labels: horizon

**Comment by bartekn** [comment] 2019-01-17 19:34
[Horizon 0.15.4](https://github.com/stellar/go/releases/tag/horizon-v0.15.4) contains a fix for this issue. Can others confirm it's working for you?

**Comment by andrenarchy** [comment] 2019-01-17 20:47
The [SatoshiPay docker images](https://hub.docker.com/r/satoshipay/stellar-horizon) have been updated to 0.15.4 and things seem to run smoothly with them. We haven't seen this issue very often though so it's hard to tell – maybe there's someone who saw that problem more frequently with the SatoshiPay images and who wants to give the new version a shot?

@bartekn thx for the fix, great job! :)

**Comment by s-a-y** [comment] 2019-01-17 21:19
I'll update my images and have a look. Thanks a lot!

**Comment by gituser** [comment] 2019-01-18 19:40
Yes, seems that `v0.15.4` fixes the issue with 504 error.

Also, I've added this to the systemd units (just to be sure):

**/etc/systemd/system/stellar-core.service**
```
[Unit]
Description=SDF - stellar-core
Before=multi-user.target
Requires=postgresql.service
After=postgresql.service
#PartOf=stellar.service

[Service]
User=stellar
Group=stellar
ExecStart=/home/stellar/stellar-core --conf /home/stellar/stellar-core.cfg
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=simple

[Install]
WantedBy=multi-user.target
```

**/etc/systemd/system/horizon.service** 
```
[Unit]
Description=SDF - stellar-horizon
Before=multi-user.target
Requires=postgresql.service stellar.service
After=postgresql.service stellar.service
#PartOf=stellar.service

[Service]
User=stellar
Group=stellar
LimitNOFILE=8192
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=stellar-horizon
EnvironmentFile=/home/stellar/.horizon-env
ExecStart=/home/stellar/horizon
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=simple

[Install]
WantedBy=multi-user.target
```

**Comment by TFiroozian** [comment] 2019-11-06 20:13
@bartekn We've experienced this issue after submitting a transaction with version 0.22.1 of the horizon many times.

```
Invalid horizon reply: [504] {'type': 'https://stellar.org/horizon-errors/timeout', 'title': 'Timeout', 'status': 504, 'detail': 'Your request timed out before completing.  Please try your request again. If you are submitting a transaction make sure you are sending exactly the same transaction (with the same sequence number).'}
``` 

Also, I don’t think this is just a TX prioritization issue caused by node/network volume.
can you check this and re-open this issue.

**Comment by ire-and-curses** [comment] 2019-11-11 17:35
@TFiroozian It's not clear to me that what you're reporting is the same issue, since others reported success after the fix in 0.15. Could you open a new one and reference this one? Thanks.

**Comment by gituser** [comment] 2021-01-07 21:26
It seems this issue is still there.

It happens from time to time: usually when there are lots of transactions being made in Stellar network.

Happens on:

`stellar-core v15.1.0`
`horizon v1.13.0`

Not sure how to debug it.

**Comment by ire-and-curses** [comment] 2021-01-07 23:46
@gituser Note that it is normal and expected to receive 504 errors when the network is under heavy load, if your provided maximum fee is insufficient. Please confirm the hash of the failed transaction, the output of /fee_stats at the time, and the fee you used. If you still feel the behaviour is incorrect, please open a new issue and include all of that information and we can take a look.

**Comment by gituser** [comment] 2021-01-08 00:23
@ire-and-curses the thing is that transaction is being included in the ledger 30 seconds later after the request.

Is there any way to get optimal fee rate for current network condition?

I think I'm using standard stellar fee.

**Comment by ire-and-curses** [comment] 2021-01-08 21:30
@gituser The general best practice is as follows:

1. Set a timebound for your transaction. This guarantees that after that time the transaction won't be accepted by the network. This protects you from e.g. sending a second duplicate payment.
2. Set an appropriate fee. If you like, you can get detailed information on the current necessary fees by querying the [fee_stats](https://horizon.stellar.org/fee_stats) endpoint, however...
3. ...Set the highest maximum fee you are comfortable with. **This doesn't mean you pay that in full on every transaction!** You will only pay whatever is necessary to get you into the ledger. So under normal circumstances, even with a higher max fee set, you will pay the standard fee (currently 100 stroops).
4. Implement a retry loop with increasing delay (e.g. 30s, 60s, 90s). This should only execute once you've exceeded the timebound you set.
5. The timeout error happens because Horizon cannot know immediately if core will include the transaction in a future ledger. Detailed information about this can be found here: https://developers.stellar.org/api/errors/http-status-codes/horizon-specific/timeout/

We're looking at improving the docs to make all of this clearer. I hope this helps.
