### ISSUE TITLE
Invalid import "bitbucket.org/ww/goautoneg"

### ISSUE THREAD

**Issue by Medasx** [stellar/go#2949] opened 2020-08-25 14:53 UTC
https://github.com/stellar/go/blob/69e628cf1cef67bbea02abc2e53ad3cddb60e4e8/services/horizon/internal/render/main.go#L6

Repo is using using mercurial which is no longer supported on Bitbucket. [More in blog post.](https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket) 

Therefore ` go get github.com/stellar/go` returns error below
```
go get: github.com/stellar/go@v0.0.0-20200820150558-f57b47851c33 requires
        bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 403 Forbidden
        server response: Repository currently not available.
```

**Comment by ire-and-curses** [comment] 2020-08-25 15:04
Yeah we need to fix this ASAP. Duplicate of #2039

**Closed by ire-and-curses** 2020-08-25 15:04 UTC
