### ISSUE TITLE
Horizon returns inconsistent fee charged for tx_bad_auth_extra

### ISSUE THREAD

**Issue by mlsteele** [stellar/go#429] opened 2018-04-30 17:28 UTC
When a transaction with extra signatures is posted, the `result_xdr` in horizon's response claims a fee was charged. But the account balance and effects don't reflect that. Was a fee really charged? If not, should `result_xdr` be changed?

[This transaction](https://www.stellar.org/laboratory/#explorer?resource=transactions&endpoint=create&values=eyJ0eCI6IkFBQUFBQy9ieTMrQmhCQkZTT0ZPR2hlbDVCWU41UUlkTVVQTzVFRGZwVnZ1ZVRoMUFBQUFaQUNGRXJZQUFBQUJBQUFBQUFBQUFBQUFBQUFCQUFBQUFBQUFBQUVBQUFBQW1uRFIxQXZYdkl2UU1SeDFwd3V0Q1c2UTNybUdTSmdKNHViTmpjL00vdkVBQUFBQUFBQUFBQkhob3dBQUFBQUFBQUFBQSs1NU9IVUFBQUJBOE13bUE0TEZqeDhsNEhZb1psZlhUMkVvNzRrcmNlV0c1NHZxcGJBeElUc1N5QWVhQzc4NTVHV090TnFRZzdUQ0lsY1JhMXZyZzliT2lYbitBV01yRHMvTS92RUFBQUJBZ0MxTTQ2WUFVNFBpRndnTktlSTFJaWE0Q2pJbU9uUUJiOHdRWFRZeEg2aUlST3ZyTzQvWmxlWE9YTEt5aVFiKzRkeXNod1RYaFBoTVhDQW1VYUphQ2ZhYnVJNEFBQUJBYnFWUVVaSktEVFN1TmZGR3poT3dqUjg2WGtmcXpUU2h0ejVKQ0xqU2s5WmhJeDRmdHBqK2Nvcmw3Q1U3a095c05DaDNnNFM4Yk1kWFpxRmJBRHdFQlE9PSJ9&network=test) has extra signatures. 

When posted horizon responds with:
```
{
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html",
  "extras": {
    "envelope_xdr": "AAAAAC/by3+BhBBFSOFOGhel5BYN5QIdMUPO5EDfpVvueTh1AAAAZACFErYAAAABAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAmnDR1AvXvIvQMRx1pwutCW6Q3rmGSJgJ4ubNjc/M/vEAAAAAAAAAABHhowAAAAAAAAAAA+55OHUAAABA8MwmA4LFjx8l4HYoZlfXT2Eo74krceWG54vqpbAxITsSyAeaC7855GWOtNqQg7TCIlcRa1vrg9bOiXn+AWMrDs/M/vEAAABAgC1M46YAU4PiFwgNKeI1Iia4CjImOnQBb8wQXTYxH6iIROvrO4/ZleXOXLKyiQb+4dyshwTXhPhMXCAmUaJaCfabuI4AAABAbqVQUZJKDTSuNfFGzhOwjR86XkfqzTShtz5JCLjSk9ZhIx4ftpj+corl7CU7kOysNCh3g4S8bMdXZqFbADwEBQ==",
    "result_codes": {
      "transaction": "tx_bad_auth_extra"
    },
    "result_xdr": "AAAAAAAAAGT////2AAAAAA=="
  }
}
```

The [result_xdr field](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAAAAAAGT%2F%2F%2F%2F2AAAAAA%3D%3D&type=TransactionResult) has `feeCharged: 100`. But the [account](https://horizon-testnet.stellar.org/accounts/GAX5XS37QGCBARKI4FHBUF5F4QLA3ZICDUYUHTXEIDP2KW7OPE4HK57J) and [effects](https://horizon-testnet.stellar.org/accounts/GAX5XS37QGCBARKI4FHBUF5F4QLA3ZICDUYUHTXEIDP2KW7OPE4HK57J/effects) endpoints don't show a debit.

**Comment by MonsieurNicolas** [comment] 2018-05-01 01:26
probably a dupe of https://github.com/stellar/go/issues/309

**Comment by mlsteele** [comment] 2018-05-01 14:33
The closest problem in https://github.com/stellar/go/issues/309 is that in that case a fee _was_ charged and the account balance changed. This issue is about when a fee is not charged, the account balance does not change, but horizon reports a fee charged in `result_xdr`.

Unless I'm misunderstanding and a fee is charged but the accounts endpoint does not reflect that.

But certainly if you still think this is a dupe feel free to close it. My guess, without knowing anything about how horizon talks to stellar-core, would be that this issue is easier to fix than https://github.com/stellar/go/issues/309.

**Comment by tomerweller** [comment] 2018-05-01 22:18
Thanks. Closing in favor of a more general issue: https://github.com/stellar/go/issues/430.

**Closed by tomerweller** 2018-05-01 22:18 UTC
