### ISSUE TITLE
SSE Stream closing without terminating chunk...

### ISSUE THREAD

**Issue by elucidsoft** [stellar/go#154] opened 2017-11-11 18:02 UTC
I opened this [issue](https://github.com/stellar/horizon/issues/414) on the other repo before realizing its been moved.

The SSE Stream is closing without issuing the terminating chunk, this is causing all sorts of issues.  You can reproduce this behavior by issuing the following command:

`curl --header "Accept: text/event-stream" https://horizon-testnet.stellar.org/accounts/GAZHWW2NBPDVJ6PEEOZ2X43QV5JUDYS3XN4OWOTBR6WUACTUML2CCJLI/transactions?limit=50`

It downloads the data and then fails at the end with the error:

`curl: (18) transfer closed with outstanding read data remaining`

I have also been able to reproduce this issue in .NET HttpClient, and Fiddler both stating that the chunk did not terminate properly.  Since this behavior violates RFC specification for chunk many clients will be unable to use the SSE Streams with Horizon.

**Comment by bartekn** [comment] 2017-11-13 15:15
I think there are a few different things related to this:
1. Clients must reconnect if connection is closed, from https://www.w3.org/TR/eventsource/:
    > Clients will reconnect if the connection is closed; a client can be told to stop reconnecting using the HTTP 204 No Content response code.
1. SDF's Horizon servers are behind ELB which automatically close connections idle for 60 seconds.
1. I don't think curl or HTTP clients are aware it's SSE connection, that's why you're seeing these strange errors. You should probably use EventSource client implementation in .Net.
1. However, it looks like Horizon does not send `close` event for your query and afaik it should do it when server side query is fulfilled. So this should be investigated.

**Comment by elucidsoft** [comment] 2017-11-13 16:56
The main issue is #4, as it's a chunked stream, most clients fail because the last chunk in stream before connection is closed is not properly terminated so the client can't tell if it was an intentional connection close and should just do a retry per the events of existing spec or if connection was interrupted and stream was incomplete.

Those two scenarios have different reconnect scenarios, if connection was interrupted you would want to restart the stream over since you can't determine accurately if there was incomplete data...

**Comment by bartekn** [comment] 2017-11-13 17:17
Correct me if I'm wrong but SSE standard requires clients to always reestablish connections, it doesn't matter if the stream was closed intentionally or not:
> The task that the networking task source places on the task queue once the fetching algorithm for such a resource (with the correct MIME type) has completed must cause the user agent to asynchronously reestablish the connection. This applies whether the connection is closed gracefully or unexpectedly.

Also, each event sent by Horizon contains id and clients should sent this value as `Last-Event-ID` when starting a new request, so it's always clear which events were sent and where to continue.

**Comment by elucidsoft** [comment] 2017-11-13 17:22
The problem is the chunk stream.  If sending as chunk stream the last chunk must be 0 bytes before connection close.

**Comment by bartekn** [comment] 2017-11-29 18:03
Can you check if it still happens to you? We had CloudFlare protection turned on and this could be a reason.

**Comment by elucidsoft** [comment] 2017-11-29 19:36
I added a try catch around my code and just reconnect now after a
termination. But I'll step through it and see if it still does it. Would be
nice to get rid of the janky try catch logic...

**Comment by bartekn** [comment] 2018-02-26 23:16
I'm closing this because I believe this is caused by ELB (AWS Elastic Load Balancer).

If you try: 
```
curl --header "Accept: text/event-stream" https://horizon-testnet.stellar.org/accounts/GAZHWW2NBPDVJ6PEEOZ2X43QV5JUDYS3XN4OWOTBR6WUACTUML2CCJLI/transactions
```
you will see that it properly closes the connection (no `curl` error) because connection is closed by Horizon. For:
```
curl --header "Accept: text/event-stream" https://horizon-testnet.stellar.org/accounts/GAZHWW2NBPDVJ6PEEOZ2X43QV5JUDYS3XN4OWOTBR6WUACTUML2CCJLI/transactions?limit=50
```
Horizon sends all the transactions for that account (less than 50 as of now) and idles until there is a new transaction connected to `GAZH...` account. Normally, Horizon would wait indefinitely but `horizon-testnet.stellar.org` is behind ELB which closes idle connections after 60 seconds. I checked ELB docs and couldn't find anything to fix this behaviour.

If you want to fix this deploy Horizon in your infrastructure.

**Closed by bartekn** 2018-02-26 23:16 UTC
Labels: in orbit
