### ISSUE TITLE
Race detected during execution of tests

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#4031] opened 2021-10-25 16:21 UTC
See https://app.circleci.com/pipelines/github/stellar/go/9661/workflows/84f9ea52-5480-449c-83e7-3e1355e1a1ed/jobs/56134

I don't have time to debug this further right now.

**Comment by sreuland** [comment] 2021-12-03 17:41
closing this as a duplicate of #4121 , it is having some problem of a shared logger/entry instance across two tests that are running simultaneously, will work on fix from that other ticket.

**Closed by sreuland** 2021-12-03 17:41 UTC
Labels: horizon, bug
