### ISSUE TITLE
exp/clients/horizon: send client headers

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#959] opened 2019-02-27 17:24 UTC
Add client headers analogous to [js-stellar-sdk#206](https://github.com/stellar/js-stellar-sdk/pull/206), to support Horizon SDK stats (#725). This is helpful to identify clients that need to be notified to upgrade.

**Comment by poliha** [comment] 2019-03-04 19:06
Duplicate of #962

**Closed by poliha** 2019-03-04 19:06 UTC
Labels: horizon, sdk
