### ISSUE TITLE
Timeout while submitting transaction to stellar network

### ISSUE THREAD

**Issue by codehakase** [stellar/go#771] opened 2018-11-21 11:53 UTC
While building a user payment op, and sending to the stellar network (testate and public nets), the sdk throws a timeout while trying to submit the transaction to the network.

Output (`*horizon.Error`)
```
err type=https://stellar.org/horizon-errors/timeout
err detailed=Your request timed out before completing.  Please try your request again. If you are submitting a transaction make sure you are sending exactly the same transaction (with the same sequence number).
err extras=
```

Sample transaction envelope generated before submitting transaction:
```
 AAAAAKN9Gxd+3LR6CiYkd28iHaR/gNFxyaNuvd/IzHVS9ilxAAAAZAABzwIAAAADAAAAAAAAAAAAAAABAAAAAQAAAACjfRsXfty0egomJHdvIh2kf4DRccmjbr3fyMx1UvYpcQAAAAEAAAAAsAuKQLbr2TPDu/xpmRFDo9YvlQcLcMdWcYyYTrXACC0AAAAAAAAAAACYloAAAAAAAAAAAbXACC0AAABAGz+ib+GsAjT3t3yii+jUXNM+DEqqbM7okXsUM+l1CQqcs3ZK9RdpdcsdrOXONIuMSYIp5I6T2Yq5a4BInJYDDw==
```

Code snippet where error is thrown from:
```go
...
tx, err := build.Transaction(
	build.SourceAccount{AddressOrSeed: a.UserKeypair().Address()},
	Network,
	build.AutoSequence{SequenceProvider: a.ClientInstance},
	build.Payment(
          build.Destination{AddressOrSeed: destination},
	  build.NativeAmount{Amount: strconv.FormatFloat(amount, 'g', -1, 64)},
	   build.SourceAccount{AddressOrSeed: a.UserKeypair().Address()},
	 )
)
if err != nil {
		return hts, fmt.Errorf("failed to build transaction, err: %v", err)
}
// sign transaction
txe, err := tx.Sign(a.AppKeypair().Seed())
if err != nil {
  return hts, fmt.Errorf("failed to sign transaction, err: %v", err)
}
txtEnvelopeStr, err := txe.Base64()
if err != nil {
	return hts, fmt.Errorf("failed to generate txt envelope str, err: %v", err)
}
resp, err := a.ClientInstance.SubmitTransaction(txtEnvelopeStr)
// err contains the timeout err
...
```

**Comment by codehakase** [comment] 2018-12-04 21:19
@bartekn mind taking a look?

**Comment by bartekn** [comment] 2018-12-07 14:31
Duplicate of https://github.com/stellar/go/issues/305.

**Closed by bartekn** 2018-12-07 14:31 UTC
