### ISSUE TITLE
intermittent CI test failures during 'go test race' condition checks on pull request(PR)

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4121] opened 2021-12-02 22:42 UTC
### What version are you using?
latest on master, currently based from v2.12.0

### What did you do?
submitted a PR, when the CI jobs ran to check the PR, one failed in `test_code_1_16` which executes:
```go test -race -coverprofile=coverage.txt -covermode=atomic ./...```

full output captured [test_code_1_16 (59649)](https://app.circleci.com/pipelines/github/stellar/go/10088/workflows/2fd1ab53-2eaa-43a6-9070-879525b0c637/jobs/59649)

if I run the same go test command locally, cannot reproduce the race errors, and upon retrying the failed CI job, it completed successfully several times afterwards. So, the occurrence is not easily replicated.

After some brief investigation on the race stack dumps provided, it appears as though two tests from unrelated/different test files are running at same time and colliding on a shared 'log' instance. 

test #1(middleware_test.go) was trying to finish and was attempting https://github.com/stellar/go/blob/master/support/log/entry.go#L211

test #2(actions_effects_test.go) was using a db session instance which tried to print a log Debugf statement https://github.com/stellar/go/blob/master/support/log/entry.go#L109

### What did you expect to see?
same passing result in CI runs as local runs for ```go test -race -coverprofile=coverage.txt -covermode=atomic ./...```

### What did you see instead?
race condition test failures on CI run. success/pass on local run.

**Comment by 2opremio** [comment] 2021-12-03 15:56
I think this is a duplicate of https://github.com/stellar/go/issues/4031 . If so, we should close #4031 since the description here is much more complete.

**Closed** 2021-12-17 17:25 UTC
Labels: bug
