### ISSUE TITLE
services/horizon: path payments via liquidity pools

### ISSUE THREAD

**Issue by Heteroculturalism** [stellar/go#4101] opened 2021-11-28 17:38 UTC
### What version are you using?

[Horizon Testnet](https://horizon-testnet.stellar.org)

### What did you do?

Executed a "swap", that is, a strict path payment to myself for one asset to another
`AAAAAgAAAABAPEGMsGRbM1VIw3l5TE3EHdrT9jgBR2g5CA5kGtRMfgAAAMgAEmFvAAAACgAAAAEAAAAAAAAAAAAAAABhonNjAAAAAAAAAAIAAAAAAAAABgAAAAJTb2xkaWVycwAAAAAAAAAACg7GN4V2JwQcc/8zzZdoU0R17Pg+fKjrRaJM/EeCA19//////////wAAAAAAAAACAAAAAVVTREMAAAAArGCmkUDdw6gF+Qhxjy7tSAOaQnMDHkmpdt0EdJBj+8gAAAACVAvkAAAAAABAPEGMsGRbM1VIw3l5TE3EHdrT9jgBR2g5CA5kGtRMfgAAAAJTb2xkaWVycwAAAAAAAAAACg7GN4V2JwQcc/8zzZdoU0R17Pg+fKjrRaJM/EeCA18AAAAAAmJaAAAAAAAAAAAAAAAAARrUTH4AAABA+G8ajYEIjjrbJsllCu+KzWIiGNZTWBrccuwTSJPyDblTeUqAEWAMDZskehGbd0Z8D9VYxCq5bWG0YR/2XxF5Dw==`

### What did you expect to see?
The transaction succeed

### What did you see instead?
A failed transaction due to "op_too_few_offers"
`AAAAAAAAAMj/////AAAAAgAAAAAAAAAGAAAAAAAAAAAAAAAC////9gAAAAA=`

[According to Horizon](https://horizon-testnet.stellar.org/paths/strict-receive?source_account=GBADYQMMWBSFWM2VJDBXS6KMJXCB3WWT6Y4ACR3IHEEA4ZA22RGH4GMB&destination_asset_type=credit_alphanum12&destination_asset_issuer=GAFA5RRXQV3COBA4OP7THTMXNBJUI5PM7A7HZKHLIWREZ7CHQIBV7SXF&destination_asset_code=Soldiers&destination_amount=4), there is such a path.

**Comment by bartekn** [comment] 2021-12-03 19:54
Duplicate of https://github.com/stellar/go/issues/4124.

**Closed by bartekn** 2021-12-03 19:54 UTC
Labels: horizon, bug
