### ISSUE TITLE
auth_immutable_flag not visible in effects

### ISSUE THREAD

**Issue by bartekn** [stellar/go#294] opened 2018-02-07 12:19 UTC
https://stellar.stackexchange.com/questions/429/confusing-effects-after-set-options-transaction

**Comment by nullstyle** [comment] 2018-03-21 14:32
This is a duplicate of https://github.com/stellar/horizon/issues/390 which has been fixed as of:  https://github.com/stellar/go/commit/e1c17a6980ae3dde6dc569c6330c5553a734b392

**Closed by nullstyle** 2018-03-21 14:32 UTC
Labels: horizon
