### ISSUE TITLE
services/horizon: Race condition in integration test

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#4992] opened 2023-07-28 13:29 UTC
Test `TestIngestionFilteringAlwaysDefaultingToTrue/ingestion_filtering_flag_set_to_false`  if failing with a race condition. See https://github.com/stellar/go/actions/runs/5691674687/job/15428169554?pr=4990 from https://github.com/stellar/go/pull/4990 

```
WARNING: DATA RACE
Write at 0x00c0003f8438 by goroutine 30721:
  runtime.racewrite()
      <autogenerated>:1 +0x24
  github.com/stellar/go/services/horizon/internal/ingest.(*system).Shutdown()
      /home/runner/work/go/go/services/horizon/internal/ingest/main.go:767 +0x150
  github.com/stellar/go/services/horizon/internal.(*App).waitForDone()
      /home/runner/work/go/go/services/horizon/internal/app.go:164 +0x164
  github.com/stellar/go/services/horizon/internal.(*App).Serve.func4()
      /home/runner/work/go/go/services/horizon/internal/app.go:133 +0x39

Previous read at 0x00c0003f8438 by goroutine 30718:
  runtime.raceread()
      <autogenerated>:1 +0x24
  github.com/stellar/go/services/horizon/internal/ingest.(*system).runStateMachine()
      /home/runner/work/go/go/services/horizon/internal/ingest/main.go:561 +0x74
  github.com/stellar/go/services/horizon/internal/ingest.(*system).Run()
      /home/runner/work/go/go/services/horizon/internal/ingest/main.go:466 +0x49
  github.com/stellar/go/services/horizon/internal.(*App).Serve.func1()
      /home/runner/work/go/go/services/horizon/internal/app.go:105 +0x5e

Goroutine 30721 (running) created at:
  github.com/stellar/go/services/horizon/internal.(*App).Serve()
      /home/runner/work/go/go/services/horizon/internal/app.go:132 +0x81d
  github.com/stellar/go/services/horizon/internal/test/integration.(*Test).StartHorizon.func4()
      /home/runner/work/go/go/services/horizon/internal/test/integration/integration.go:453 +0x55
```

**Comment by aditya1702** [comment] 2023-07-28 15:09
Closing since this a duplicate of #4987

**Closed by aditya1702** 2023-07-28 15:09 UTC
